import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { CartProvider } from "./context/cardContext";
import { FavoriteProvider } from "./context/favContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Furniture Ecommerce MarketPlace",
  description: "Generated by Developer Hammad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FavoriteProvider>
        <CartProvider>
        {children}
        </CartProvider>
        </FavoriteProvider>
        <Footer/>
      </body>
    </html>
  );
}
